### ISSUE TITLE
The episode player half-hidden 

### ISSUE THREAD

**Issue by vicainelli** [zofepod/zofe#151]
The episode player is half-hidden when I click on the player button "Escutar este episório" I can see only part of the bottom bar player.

Here are some screenshots

<img width="1484" alt="Screenshot 2021-04-08 at 11 16 37" src="https://user-images.githubusercontent.com/1155694/114004263-c5559480-985e-11eb-80d9-4f47933f83c1.png">    

_Source Chrome 89.0.4389.114 (Official Build) (x86_64) on macOS Big Sur 11.2.3_
The behavior is the same on Firefox, Safari, and Brave.

Also,  I recorded a video on chrome asl well

https://user-images.githubusercontent.com/1155694/114005042-7825f280-985f-11eb-998f-917036ce7f8e.mov

**Comment by danielfilho** [comment]
There's an issue: the problem here is the player and all its styling.

Your change makes it nice on Chrome, but now it hides the footer on Firefox, and also it looks weird there like my image attached.

I was going to make a simple but consistent player accross different browsers. I will merge this PR but will need to refine a bit the player anyways 🤷 

Thanks for taking care of it ❤️ 

![zofe](https://user-images.githubusercontent.com/24597/114174162-8ac02a80-9938-11eb-9aed-e027e51a02d5.gif)

**Comment by vicainelli** [comment]
Yeah, there are some inconsistencies between the browsers, and also on mobile, the player doesn't show because of the navbar.

I would test locally, there's mocked data to run the API locally?
Since the APP request a Contentful credential to load the data.
